#ifndef ROBLOX_STUDIO_VERSION_H
#define ROBLOX_STUDIO_VERSION_H

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VER_FILEVERSION             21,04,2026,2
#define VER_FILEVERSION_STR         TOSTRING(VER_FILEVERSION)

#define VER_PRODUCTVERSION          21,04,2026,0
#define VER_PRODUCTVERSION_STR      TOSTRING(VER_PRODUCTVERSION)

#define VER_COMPANYNAME_STR         "GraceRBLX"
#define VER_FILEDESCRIPTION_STR     "ANORRL Studio"
#define VER_INTERNALNAME_STR        "ANORRL Studio Qt"
#define VER_LEGALCOPYRIGHT_STR      "Copyright © 2026 GraceRBLX"
#define VER_LEGALTRADEMARKS1_STR    "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR    "RobloxStudio.exe"
#define VER_PRODUCTNAME_STR         "ANORRL Studio"

#endif // ROBLOX_STUDIO_VERSION_H
