#if defined(_WIN32)
#include "arl/Crypt.h"

#include "rbxFormat.h"
#include <atlenc.h>
#include <iomanip>
#include <sstream>

#include "arl/Debug.h"

namespace ARL {

Crypt::Crypt()
{
	static const char* keyB64 = "BgIAAACkAABSU0ExAAQAAAEAAQCBPABEhp0z0LK9c3BYdM2Tl02R3liAFVInOcO8L46wAAOpbGlbN1v+GO7DWvOaLpAxT1bw3XTzv8PHWCUZZlXQZB4HEK2jDOuDjgOE55uKfFjlQNBHPdf8uKN4j2SR65u+UEO/YeknNScY6aZ50plPr5stWzVWUaHsehO5gFEGyQ==";
	char pbKeyBlob[256];
	int dwBlobLen = 256;

	// http://support.microsoft.com/kb/238187
	if (!CryptAcquireContext(&context, NULL, MS_DEF_PROV, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT))
	{
		if (::GetLastError()==NTE_BAD_KEYSET)
		{
			if (!CryptAcquireContext(&context, NULL, MS_DEF_PROV, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT | CRYPT_NEWKEYSET))
				throw ARL::runtime_error("Error %x during CryptAcquireContext 2\n", GetLastError());
		}
		else
			throw ARL::runtime_error("Error %x during CryptAcquireContext\n", GetLastError());
	}

	
	{		
		ATL::Base64Decode(keyB64, strlen(keyB64), (BYTE*)pbKeyBlob, &dwBlobLen);
	}

	if (!CryptImportKey(context, (BYTE*)pbKeyBlob, dwBlobLen, 0, 0, &key))
		 throw ARL::runtime_error("Error %x during CryptImportKey", GetLastError());
}

Crypt::~Crypt()
{
	CryptDestroyKey(key);
	CryptReleaseContext(context, 0);
}

void Crypt::verifySignatureBase64(std::string message, std::string signatureBase64)
{
	HCRYPTHASH hash;
	if (!CryptCreateHash(context, CALG_SHA1, NULL, 0, &hash))
#ifdef _DEBUG
		 throw ARL::runtime_error("Error %x during CryptCreateHash", GetLastError());
#else
		 throw ARL::runtime_error("");
#endif
	try
	{
		if (!CryptHashData(hash, (BYTE*)message.c_str(), message.size(), 0))
#ifdef _DEBUG
			throw ARL::runtime_error("Error %x during CryptHashData", GetLastError());
#else
			throw ARL::runtime_error("");
#endif
		int signatureLen = Base64DecodeGetRequiredLength(signatureBase64.size());
		BYTE* signature = (BYTE*)alloca(signatureLen);
		ATL::Base64Decode(signatureBase64.c_str(), signatureBase64.size(), signature, &signatureLen);
		
		/*
			The native cryptography API uses little-endian byte order 
			while the .NET Framework API uses big-endian byte order. 
			If you are verifying a signature generated by using a .NET Framework 
			API, you must swap the order of signature bytes before calling the 
			CryptVerifySignature function to verify the signature.
		*/
		BYTE signatureRev[10240];
		// FUCK YOU ROBLOX!!!
		for (int i=0; i < signatureLen && i <= 10240; ++i)
			signatureRev[i] = signature[signatureLen - i - 1];

#pragma warning(push)
#pragma warning(disable: 6309)
#pragma warning(disable: 6387)
		if (!CryptVerifySignature(hash, signatureRev, signatureLen, key, NULL, 0))
#ifdef _DEBUG
			throw ARL::runtime_error("CryptVerifySignature Error 0x%x. sigLen=%d sigB64='%s' message='%s'", GetLastError(), signatureLen, signatureBase64.c_str(), message.c_str());
#else
			throw ARL::runtime_error("");
#endif
#pragma warning(pop)
	}
	catch (...)
	{
		::CryptDestroyHash(hash);
		throw;
	}

	::CryptDestroyHash(hash);
}

} //namespace ARL

#else

#include "arl/Crypt.h"

namespace ARL
{

Crypt::Crypt() {}
Crypt::~Crypt() {}
void Crypt::verifySignatureBase64(std::string message, std::string signatureBase64) {}

}

#endif



