include(Base)

include_project_files(Base "*")

include_directories(include)

if(ANDROID)
  list(APPEND HEADERS include/arl/Android/ifaddrs.h)
  list(APPEND SOURCES arl/Android/ifaddrs.c)
  list(APPEND SOURCES arl/Android/SystemUtil.cpp)
  list(APPEND SOURCES arl/Android/SystemUtil.cpp)
elseif(WIN32)
  list(APPEND HEADERS arl/Win/WindowsUtil.h)

  list(APPEND SOURCES arl/Win/WindowsUtil.cpp)
  list(APPEND SOURCES arl/Crypt.cpp)
  list(APPEND SOURCES arl/Win/SystemUtil.cpp)
  list(APPEND SOURCES util/RegistryUtil.cpp)
elseif(APPLE)
  list(APPEND SOURCES arl/Darwin/SystemUtil.cpp)
elseif(UNIX AND NOT ANDROID)
  list(APPEND SOURCES arl/Unix/SystemUtil.cpp)
  list(APPEND SOURCES arl/Unix/Crypt.cpp)
endif(ANDROID)

list(APPEND HEADERS include/HardwareInfo.h)
list(APPEND HEADERS include/ARLFormat.h)
list(APPEND HEADERS include/ARLPlatform.h)
list(APPEND HEADERS include/ARLHash.h)
list(APPEND HEADERS include/ARLBase.h)
list(APPEND HEADERS include/arl/ProcessPerfCounter.h)
list(APPEND HEADERS include/arl/object_pool.h)
list(APPEND HEADERS include/arl/signal.h)
list(APPEND HEADERS include/arl/RbxDbgInfo.h)
list(APPEND HEADERS include/arl/RbxStrings.h)
list(APPEND HEADERS include/arl/CEvent.h)
list(APPEND HEADERS include/arl/Tasks/Coordinator.h)
list(APPEND HEADERS include/arl/threadsafe.h)
list(APPEND HEADERS include/arl/DenseHash.h)
list(APPEND HEADERS include/arl/GlobalVectorItem.h)
list(APPEND HEADERS include/arl/TaskScheduler.Job.h)
list(APPEND HEADERS include/arl/RunningAverage.h)
list(APPEND HEADERS include/arl/TaskScheduler.h)
list(APPEND HEADERS include/arl/Debug.h)
list(APPEND HEADERS include/arl/atomic.h)
list(APPEND HEADERS include/arl/intrusive_weak_ptr.h)
list(APPEND HEADERS include/arl/Intrusive/Set.h)
list(APPEND HEADERS include/arl/rbxTime.h)
list(APPEND HEADERS include/arl/BaldPtr.h)
list(APPEND HEADERS include/arl/make_shared.h)
list(APPEND HEADERS include/arl/Memory.h)
list(APPEND HEADERS include/arl/Log.h)
list(APPEND HEADERS include/arl/SystemUtil.h)
list(APPEND HEADERS include/arl/callable.h)
list(APPEND HEADERS include/arl/MathUtil.h)
list(APPEND HEADERS include/arl/intrusive_ptr_target.h)
list(APPEND HEADERS include/arl/Declarations.h)
list(APPEND HEADERS include/arl/Crypt.h)
list(APPEND HEADERS include/arl/Nil.h)
list(APPEND HEADERS include/arl/trie.h)
list(APPEND HEADERS include/util/RegistryUtil.h)
list(APPEND HEADERS include/util/ublas_ext.h)
list(APPEND HEADERS include/util/stringbuffer.h)
list(APPEND HEADERS include/util/SafeToLower.h)
list(APPEND HEADERS include/util/ScopedSingleton.h)
list(APPEND HEADERS include/SelectState.h)
list(APPEND HEADERS include/CPUCount.h)
list(APPEND HEADERS include/ARLAssert.h)

list(APPEND SOURCES ../ClientShared/Mobile/CookiesEngine.cpp)
list(APPEND SOURCES ../ClientShared/SimpleJSON.cpp)
list(APPEND SOURCES ../ClientShared/format_string.cpp)

list(APPEND SOURCES cpucount.cpp)
list(APPEND SOURCES ARLAssert.cpp)
list(APPEND SOURCES ARLFormat.cpp)

list(APPEND SOURCES arl/MathUtil.cpp)
list(APPEND SOURCES arl/boost.cpp)
list(APPEND SOURCES arl/CEvent.cpp)
list(APPEND SOURCES arl/Memory.cpp)
list(APPEND SOURCES arl/ProcessPerfCounter.cpp)
list(APPEND SOURCES arl/Profiler.cpp)
list(APPEND SOURCES arl/Signal.cpp)
list(APPEND SOURCES arl/TaskScheduler.cpp)
list(APPEND SOURCES arl/TaskScheduler.Job.cpp)
list(APPEND SOURCES arl/TaskScheduler.Thread.cpp)
list(APPEND SOURCES arl/ThreadSafe.cpp)
list(APPEND SOURCES arl/Time.cpp)
list(APPEND SOURCES include/arl/RbxDbgInfo.cpp)

list(APPEND SOURCES arl/Tasks/Coordinator.cpp)

list(APPEND SOURCES util/Debug.cpp)
list(APPEND SOURCES util/Log.cpp)
list(APPEND SOURCES util/RbxCrash.cpp)
list(APPEND SOURCES util/StreamHelpers.cpp)

add_library(Base OBJECT ${SOURCES} ${HEADERS})
